### ISSUE TITLE
Définir le séparateur pour les valeurs multiples

### ISSUE THREAD

**Issue by marc-gavanier** [LaMednum/standard-mediation-num#10]
Actuellement il coexiste trois formats pour séparer les valeurs des champs qui peuvent avoir de multiples valeurs :
- Virgule `,` - on peut trouver ce cas dans la documention du schéma de données des lieux de médiation numérique [pour l'exemple du champ `services`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-19), ainsique  [pour l'exemple du champ `site_web`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-12)
- Virgule  avec espace `, ` - on peut trouver ce cas dans la documention du schéma de données des lieux de médiation numérique [pour l'exemple du champ `typologie`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-9), ainsi que  [pour l'exemple du champ `publics_accueillis`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-20), [`conditions_access`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-21), [`labels_nationaux`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-22), [`labels_autres`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-23) et [`modalites_accompagnement`](https://lamednum.coop/schema-de-donnees-des-lieux-de-mediation-numerique-2/#elementor-toc__heading-anchor-24)
- Point virgule `;` - on peut trouver ce cas pour l'ensemble des champs multiples [du schéma au format JSON](https://github.com/LaMednum/standard-mediation-num/blob/main/schema.json)

Idéalement il faudrait opter pour le séparateur qui correspond le mieux aux usages des collecteurs de données.

**Comment by marc-gavanier** [comment]
Open Data France recommande [l'utilisation des points-virgules dans ce cas](https://scdl.opendatafrance.net/docs/recommandations-relatives-aux-jeux-de-donnees.html).
> le séparateur de valeurs multiples dans un champ est le point-virgule

**Comment by EliseHPC** [comment]
Merci @marc-gavanier d'avoir relevé les incohérences. Dans le json j'ai modifié l'exemple pour utiliser le point virgule dans le champ `site_web`, en principe tout est harmonisé dans le schéma. 
On va vérifier la documentation.
